#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /api/login_check

gpmb:
   path: /gpmb
   controller: App\Service\GPMB\AgregaGenerator::index
